### ISSUE TITLE
db.connect() is hanging after few calls made to the database

### ISSUE THREAD

**Issue by himadric** [vercel/storage#177] opened 2023-06-05 03:18 UTC
I have created some functions to read and write data from Postgres database following the example provided in the doc [](https://vercel.com/docs/storage/vercel-postgres/quickstart#populate-your-database)

Also, as per the documentation using db is the most efficient way to interact with the database, but it's hanging the connection after a certain number of calls. I suspect it is something to do with the client pool. 

```ts
import { db } from "@vercel/postgres";
export async function PhotoViews(photo_id: string) {
    const client = await db.connect();
  try {
    const result =
      await client.sql`SELECT COUNT(*) AS COUNT FROM photo_views WHERE photo_id = ${photo_id};`;
    return result.rows[0];
  } catch (error) {
    throw error;
  } 
}
```

If I switch my code to use createClient() I don't see the problem. Here is the same function using createClient().

```ts
import { createClient } from "@vercel/postgres";
export async function PhotoViews(photo_id: string) {
  const client = createClient();
  await client.connect();
  //const client = await db.connect();
  try {
    const result =
      await client.sql`SELECT COUNT(*) AS COUNT FROM photo_views WHERE photo_id = ${photo_id};`;
    return result.rows[0];
  } catch (error) {
    throw error;
  } finally {
    client.end();
  }
}
```

**Comment by niccolo92matinum** [comment] 2023-06-07 21:34
I had the same issue........with your code it is solved.  Thanks

**Comment by adriancooney** [comment] 2023-06-28 13:53
I was able to reproduce this issue with your code, thanks for the report. The problem here is that we are acquiring a connection from the pool but not releasing it back to the pool when we are finished. You second code snippet is creating a new pool each time the function is called and releasing all connections in the pool when it's completed. We can update your first snippet to release the connection back to the pool:

```ts
import { db } from "@vercel/postgres";

export async function PhotoViews(photo_id: string) {
  const client = await db.connect();

  try {
    const result =
      await client.sql`SELECT COUNT(*) AS COUNT FROM photo_views WHERE photo_id = ${photo_id};`;
    return result.rows[0];
  } finally {
    client.release();
  }
}
```

This should fix your issue (fixed mine locally). It's worth noting that if you're deploying this to a serverless environment (like Vercel), you won't see these connection issues because there is no shared state between requests. 

Finally, if you're only executing a single query, you can import the default connection to simplify things:

```ts
import { sql } from "@vercel/postgres";

export async function PhotoViews(photo_id: string) {
  const result =
    await sql`SELECT COUNT(*) AS COUNT FROM photo_views WHERE photo_id = ${photo_id};`;

  return result.rows[0];
}
```

It automatically manages the connections via the default pool.

Since there's no bug or documentation update needed here, I'm going to close this out. Feel free to re-open if you feel the issue is not resolved! Thanks.

**Closed as completed by adriancooney** 2023-06-28 13:53 UTC
Labels: storage: postgres

**Comment by himadric** [comment] 2023-06-30 02:32
@adriancooney  thanks for the answer. Just want to point out that the example provided in the quickstart document doesn't have client.release(). 

import { db } from '@vercel/postgres';
import { NextApiRequest, NextApiResponse } from 'next';
 
export default async function handler(
  request: NextApiRequest,
  response: NextApiResponse,
) {
  const client = await db.connect();
 
  try {
    await client.sql`CREATE TABLE Pets ( Name varchar(255), Owner varchar(255) );`;
    const names = ['Fiona', 'Lucy'];
    await client.sql`INSERT INTO Pets (Name, Owner) VALUES (${names[0]}, ${names[1]});`;
  } catch (error) {
    return response.status(500).json({ error });
  }
 
  const pets = await client.sql`SELECT * FROM Pets;`;
  return response.status(200).json({ pets });
}
